SELECT C7_NUM 
	, C7_ITEM
	, C7_PRODUTO
	, C7_DESCRI
	, C7_QUANT
	, C7_PRECO
	, C7_TOTAL
	, C7_OBS
	, C7_FORNECE
	, A2_NOME
	, CONVERT(DATE, C7_EMISSAO) AS EMISSAO
    FROM SC7010
		INNER JOIN SA2010 ON A2_COD = C7_FORNECE AND SA2010.D_E_L_E_T_ <> '*'
	WHERE C7_PRODUTO LIKE 'BF%'
		AND C7_EMISSAO LIKE '202%'
		AND SC7010.D_E_L_E_T_ <>'*'
		AND C7_FILIAL = '01'