WITH OP_NOV AS (
	SELECT						--
		D4_COD AS Produto,
		B1.B1_DESC AS DESCRIÇÃO,
		D4_LOCAL AS Armazem,
		D4_OP AS NUMERO_OP,
		D4_DATA AS DT_Empenho,
		D4_QTDEORI AS Qtd_Empenho,
		D4_PRODUTO AS Produto_Pai,
		--B2.B1_DESC AS DESCRIÇÃO_PAI,
		B1.B1_GRUPO AS Grupo

		FROM 
			SD4010 D 
			INNER JOIN SB1010 B2 ON D4_PRODUTO = B1_COD
			INNER JOIN SB1010 B1 ON	D4_COD = B1.B1_COD


		WHERE B1.B1_GRUPO = '021N' AND --CAMPO A SER ALTERADO CONFORME O GRUPO A SER PESQUISADO--
			LEFT (D4_OP, LEN(D4_OP)-5) IN
			( 'A00ZXE','A00ZXF','A00ZXG','A00ZXH','A00ZXI','A00ZXJ','A00ZXK','A00ZXL','A00ZXM','A00ZXP','A00ZXQ','A00ZXR','A00ZXS','A00ZXT','A00ZXU','A01243','A01183') --OPS DE JANEIRO--
			AND	b1.D_E_L_E_T_ <> '*'
	)
SELECT 
	Produto,
	DESCRIÇÃO,
	Armazem,
	LEFT (NUMERO_OP, LEN(NUMERO_OP)-5) AS OP,
	C2_OBS,
	SUBSTRING(C2_OBS, CHARINDEX('-', C2_OBS)+ 1, (LEN(trim(C2_OBS)) - CHARINDEX('-', C2_OBS, 7) ) )AS RESULTADO,
	len(c2_obs),
	--CHARINDEX('-', C2_OBS, 7),
	DT_Empenho,
	Qtd_Empenho,
	Produto_Pai,
	Grupo
	FROM 
		OP_NOV
		INNER JOIN SC2010 ON C2_OP = OP_NOV.NUMERO_OP AND SC2010.D_E_L_E_T_<>'*'

