--LEAD TIME CAMES: PRAZO DE ENTREGA DOS BFH + DECRI: CAMES-------------------------------------------------------------- 

SELECT B1_COD AS CODIGO,
	B1_DESC AS DESCR,
    B1_PE AS PRAZO_ENTR
	FROM SB1010
	WHERE B1_COD LIKE 'BFH%'
		AND B1_DESC LIKE 'CAME%'

--A PARTIR DA TABELA ANTERIOR, INCLUIMOS C7(P. DE COMPRAS) E FILTRAMOS AS SAIDAS DESSE ANO-------------------------------

SELECT A.B1_COD, 
	A.B1_DESC,
	C7_NUM, 
	C7_ITEM, 
	C7_QUANT, 
	C7_OBS
	FROM(SELECT B1_COD,	
			B1_DESC, 
			B1_PE
			FROM SB1010
			WHERE B1_COD LIKE 'BFH%'
				AND B1_DESC LIKE 'CAME%') A
	INNER JOIN SC7010 ON B1_COD = C7_PRODUTO
	WHERE C7_EMISSAO BETWEEN '20240101' AND '20240801'
	ORDER BY C7_NUM

--A PARTIR DAS SAIDA DESSE ANO (CONSULTA ANTERIOR), SOMAMOS A QUANTIDAE DE CADA PRODUTO ENVIADO----------------------------------------------

SELECT DISTINCT(A.B1_COD), 
	A.B1_DESC, 
	SUM(C7_QUANT) AS PROD_2024
	FROM(SELECT A.B1_COD, 
		 A.B1_DESC, 
		 C7_QUANT
		FROM(SELECT B1_COD, 
			 B1_DESC
			 FROM SB1010
			 WHERE B1_COD LIKE 'BFH%'
				 AND B1_DESC LIKE 'CAME%') A
	INNER JOIN SC7010 ON B1_COD = C7_PRODUTO
	WHERE C7_EMISSAO BETWEEN '20240101' AND '20240801') A
	GROUP BY A.B1_COD, A.B1_DESC
	ORDER BY PROD_2024 DESC



SELECT *
	FROM(SELECT B1_COD AS CODIGO,
			B1_DESC AS DESCR,
			B1_PE AS PRAZO_ENTR,
			B1_grupo,
			G1_COD
		FROM SB1010
		INNER JOIN SG1010 ON B1_COD = G1_COMP
		WHERE B1_COD LIKE 'BFC%'
			AND B1_DESC LIKE 'BLOCO%') A

	
