--CONSULTA PESO POR CÓDIGO APROXIMADO --------------------

SELECT * 
	FROM SC1010
	WHERE C1_PRODUTO LIKE 'BF%' 
		AND C1_OBS IS NOT NULL 
		AND C1_PRODUTO in ('BFH0010029L')
	ORDER BY C1_EMISSAO DESC;


-- CONSULTAR PESO POR DESCRIÇÃO E FORNECEDOR -------------------

SELECT C7_DESCRI, * 
	FROM SC7010
	WHERE C7_PRODUTO LIKE 'BFC%'
		AND C7_FORNECE = '003659'
		AND C7_DESCRI LIKE 'ANEL%'
		AND C7_DESCRI LIKE '%34%'